// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using database.Data;

#nullable disable

namespace database.Migrations
{
    [DbContext(typeof(MetroDbContext))]
    partial class MetroDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("database.Models.LineInfo", b =>
                {
                    b.Property<long>("LineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("line_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("LineCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("line_code");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("line_name");

                    b.Property<long>("OperatorId")
                        .HasColumnType("bigint")
                        .HasColumnName("operator_id");

                    b.HasKey("LineId");

                    b.HasIndex("OperatorId");

                    b.ToTable("line_info", (string)null);
                });

            modelBuilder.Entity("database.Models.OperatorInfo", b =>
                {
                    b.Property<long>("OperatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("operator_id");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("contact_person");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("OperatorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("operator_code");

                    b.Property<string>("OperatorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("operator_name");

                    b.HasKey("OperatorId");

                    b.ToTable("operator_info", (string)null);
                });

            modelBuilder.Entity("database.Models.SectionInfo", b =>
                {
                    b.Property<long>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("section_id");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("distance_km");

                    b.Property<long>("FromStationId")
                        .HasColumnType("bigint")
                        .HasColumnName("from_station_id");

                    b.Property<bool>("IsBidirectional")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_bidirectional");

                    b.Property<long>("LineId")
                        .HasColumnType("bigint")
                        .HasColumnName("line_id");

                    b.Property<long>("ToStationId")
                        .HasColumnType("bigint")
                        .HasColumnName("to_station_id");

                    b.HasKey("SectionId");

                    b.HasIndex("LineId");

                    b.ToTable("section_info", (string)null);
                });

            modelBuilder.Entity("database.Models.StationInfo", b =>
                {
                    b.Property<long>("StationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("station_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsTransfer")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_transfer");

                    b.Property<string>("StationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("station_code");

                    b.Property<string>("StationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("station_name");

                    b.HasKey("StationId");

                    b.ToTable("station_info", (string)null);
                });

            modelBuilder.Entity("database.Models.TicketTransaction", b =>
                {
                    b.Property<long>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("transaction_id");

                    b.Property<string>("CardNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("card_no");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long?>("EntryStationId")
                        .HasColumnType("bigint")
                        .HasColumnName("entry_station_id");

                    b.Property<DateTime?>("EntryTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("entry_time");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("exception_type");

                    b.Property<long?>("ExitStationId")
                        .HasColumnType("bigint")
                        .HasColumnName("exit_station_id");

                    b.Property<DateTime?>("ExitTime")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("exit_time");

                    b.Property<decimal>("PayAmount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("pay_amount");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("payment_type");

                    b.Property<string>("TransactionStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("transaction_status");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("transaction_type");

                    b.HasKey("TransactionId");

                    b.ToTable("ticket_transaction", (string)null);
                });

            modelBuilder.Entity("database.Models.LineInfo", b =>
                {
                    b.HasOne("database.Models.OperatorInfo", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("database.Models.SectionInfo", b =>
                {
                    b.HasOne("database.Models.LineInfo", "Line")
                        .WithMany()
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Line");
                });
#pragma warning restore 612, 618
        }
    }
}
